-- Oracle PL/SQL: tenant-owner matching + notification records
CREATE TABLE tenant_interest (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_email VARCHAR2(255) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    locality VARCHAR2(100),
    budget NUMBER NOT NULL,
    bhk NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE owner_notification (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_email VARCHAR2(255) NOT NULL,
    tenant_email VARCHAR2(255) NOT NULL,
    property_id NUMBER NOT NULL,
    message VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE PROCEDURE notify_owner_matches IS
BEGIN
    INSERT INTO owner_notification (owner_email, tenant_email, property_id, message)
    SELECT p.owner_email,
           t.tenant_email,
           p.id,
           'New tenant match for property #' || p.id || ' from ' || t.tenant_email
      FROM tenant_interest t
      JOIN property p
        ON p.city = t.city
       AND p.locality = t.locality
       AND p.rent <= t.budget
       AND p.bhk = t.bhk
       AND p.moderation_status = 'APPROVED'
       AND p.active = 1;
END;
/
